CREATE TABLE IF NOT EXISTS stock_fundamentals (
    ticker                   TEXT PRIMARY KEY,
    company_name             TEXT,

    rep_no                   TEXT,
    org_perm_id              TEXT,
    isin                     TEXT,
    ric                      TEXT,
    exchange_code            TEXT,
    exchange_country         TEXT,
    most_recent_split_date   DATE,
    most_recent_split_factor NUMERIC,

    mkt_cap_usd              NUMERIC,
    pe_ratio                 NUMERIC,
    price_to_book            NUMERIC,
    price_to_revenue         NUMERIC,
    ev                       NUMERIC,
    ebitda                   NUMERIC,
    revenue_annual           NUMERIC,
    net_income_annual        NUMERIC,
    roe_pct                  NUMERIC,
    gross_margin_pct         NUMERIC,
    dividend_yield_pct       NUMERIC,
    dividend_per_share       NUMERIC,
    eps_basic                NUMERIC,
    revenue_per_share        NUMERIC,
    book_value_per_share     NUMERIC,
    cash_per_share           NUMERIC,
    cash_flow_per_share      NUMERIC,

    target_price             NUMERIC,
    proj_pe                  NUMERIC,
    proj_eps                 NUMERIC,
    proj_eps_q               NUMERIC,
    proj_sales               NUMERIC,
    proj_sales_q             NUMERIC,
    proj_profit              NUMERIC,
    proj_dps                 NUMERIC,
    proj_lt_growth           NUMERIC,
    recommendation_score     NUMERIC,

    xml_52w_low              NUMERIC,
    xml_52w_high             NUMERIC,
    xml_last_price           NUMERIC,
    xml_vol_10d_avg          NUMERIC,
    xml_last_price_date      DATE,

    co_status                TEXT,
    co_type                  TEXT,
    latest_annual_date       DATE,
    latest_interim_date      DATE,
    employees                INTEGER,
    shares_out               NUMERIC,
    shares_out_date          DATE,
    total_float              NUMERIC,
    reporting_currency       TEXT,
    most_recent_exch_date    DATE,
    most_recent_exch_val     NUMERIC,

    industry_trbc            TEXT,
    industry_trbc_code       TEXT,
    industry_naics           TEXT,
    industry_naics_code      TEXT,
    industry_sic             TEXT,
    industry_sic_code        TEXT,

    address                  TEXT,
    city                     TEXT,
    postal_code              TEXT,
    country_code             TEXT,
    phone                    TEXT,
    website                  TEXT,
    email                    TEXT,

    business_summary         TEXT,
    financial_summary        TEXT,

    officer_1_name           TEXT,
    officer_1_title          TEXT,
    officer_2_name           TEXT,
    officer_2_title          TEXT,
    officer_3_name           TEXT,
    officer_3_title          TEXT,
    officer_4_name           TEXT,
    officer_4_title          TEXT,
    officer_5_name           TEXT,
    officer_5_title          TEXT,
    officers_json            JSONB,

    price_currency           TEXT,
    last_fundamental_update  TIMESTAMP
);
